### ISSUE TITLE
input-output format

### ISSUE THREAD

**Issue by NLPCL** [nlpcl-lab/mitigating-stereotypes-in-word-embedding#1]
hi, @huijelee, I am doing the end-of-the-year check up.

the example result format is clear.
Yet, I find that it is confounding how I can put a sentence that I choose
and get the result.

if possible, please put the material in the README file,
such as "python main.py --input_sentence input_file.txt --ouput output_file.txt"

thanks, yours sincerely, Yang

**Comment by huijelee** [comment]
Unfortunately, the mitigated output for sentence is not yet developed. To handle sentence-level input, you can import the output embedding of our word embedding model and test it by applying simple CNN or RNN based sentence encoder.
